name: MCClock
description: An analog clock.
version: '${version}'
main: moe.minhh2792.mcclock.MCClock
api-version: '1.13'
authors: [ minhh2792 ]

commands:
  mcclock:
    description: MCClock commands
    aliases: [ mcc ]
    usage: /mcclock <get|getframe|place|reload>
    permission: mcclock.admin

permissions:
  mcclock.admin:
    description: Allows getting the clock map
    default: op
